"use client";

import { ArrowLeft, BookOpen, CheckCircle2, ChevronRight, Database, ExternalLink, LockKeyhole, Presentation, ServerCog, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { useState, type ReactNode } from "react";

import AppShell from "@/components/layout/AppShell";
import styles from "./SystemDocumentation.module.css";

type DocumentId = "presentation" | "manual" | "security" | "migration";

const documents = [
  { id: "presentation" as const, title: "Apresentação", subtitle: "Do problema à visão de futuro", description: "Roteiro executivo para apresentar o contexto, o nascimento e o potencial do Robot Center.", icon: Presentation, audience: "Gestores e lideranças" },
  { id: "manual" as const, title: "Manual de Uso", subtitle: "Operação diária e administração", description: "Guia funcional para gestores, administradores e equipes que utilizam o Robot Center.", icon: BookOpen, audience: "Gestores e usuários" },
  { id: "security" as const, title: "Documentação de Segurança", subtitle: "Arquitetura, controles e operação segura", description: "Referência técnica para Infraestrutura, Segurança da Informação e responsáveis pela plataforma.", icon: ShieldCheck, audience: "Infraestrutura e Segurança" },
  { id: "migration" as const, title: "Possibilidades de Migração", subtitle: "Banco interno ou não relacional", description: "Análise de alternativas para PostgreSQL interno, MongoDB e modelos híbridos.", icon: Database, audience: "Gestores e Arquitetura" },
];

export default function SystemDocumentation() {
  const [active, setActive] = useState<DocumentId | null>(null);
  const selected = documents.find((document) => document.id === active);

  return <AppShell title="Documentação do Sistema">
    <div className={styles.page}>
      <header className={styles.hero}>
        <div><span className={styles.eyebrow}>ROBOT CENTER · DOCUMENTAÇÃO EXECUTIVA</span><h1>Documentação do Sistema</h1><p>Visão funcional, segurança da plataforma e caminhos possíveis para evolução da arquitetura.</p></div>
        <Link href="/minha-pagina" className={styles.back}><ArrowLeft size={14} /> Voltar ao sistema</Link>
      </header>

      {!active ? <>
        <section className={styles.intro}><div className={styles.introIcon}><LockKeyhole size={22} /></div><div><strong>Área reservada à administração Master</strong><p>Documentos institucionais preparados para apresentação e apoio à tomada de decisão. O conteúdo não altera configurações nem dados do Robot Center.</p></div></section>
        <div className={styles.cards}>{documents.map((document) => { const Icon = document.icon; return <button key={document.id} type="button" className={styles.card} onClick={() => setActive(document.id)}><span className={styles.cardIcon}><Icon size={21} /></span><span className={styles.cardContent}><small>{document.subtitle}</small><strong>{document.title}</strong><p>{document.description}</p><span className={styles.audience}><Users size={12} /> {document.audience}</span></span><ChevronRight className={styles.cardArrow} size={18} /></button>; })}</div>
        <section className={styles.footerNote}><ServerCog size={18} /><div><strong>Documento vivo</strong><p>O material deve ser revisado quando houver mudança relevante de infraestrutura, autenticação, permissões ou persistência.</p></div></section>
      </> : <article className={styles.document}>
        <nav className={styles.documentNav}><button type="button" onClick={() => setActive(null)}><ArrowLeft size={13} /> Todos os documentos</button>{documents.map((document) => <button key={document.id} type="button" className={active === document.id ? styles.active : undefined} onClick={() => setActive(document.id)}>{document.title}</button>)}</nav>
        <header className={styles.documentHeader}>{selected && <><span className={styles.documentIcon}>{<selected.icon size={23} />}</span><div><small>{selected.subtitle}</small><h2>{selected.title}</h2><p>{selected.description}</p></div></>}</header>
        {active === "manual" && <Manual />}
        {active === "security" && <Security />}
        {active === "migration" && <Migration />}
        {active === "presentation" && <ExecutivePresentation />}
      </article>}
    </div>
  </AppShell>;
}

function Section({ number, title, children }: { number: string; title: string; children: ReactNode }) {
  return <section className={styles.section}><header><span>{number}</span><h3>{title}</h3></header><div>{children}</div></section>;
}

function Callout({ title, children, tone = "blue" }: { title: string; children: ReactNode; tone?: "blue" | "green" | "amber" }) {
  return <aside className={`${styles.callout} ${styles[tone]}`}><strong>{title}</strong><div>{children}</div></aside>;
}

function Checklist({ items }: { items: string[] }) {
  return <ul className={styles.checklist}>{items.map((item) => <li key={item}><CheckCircle2 size={14} />{item}</li>)}</ul>;
}

function Manual() {
  return <div className={styles.body}>
    <Section number="01" title="Objetivo do Robot Center"><p>O Robot Center centraliza o catálogo de robôs, documentação operacional, fluxos, solicitações de Stack, atualizações e indicadores. A plataforma cria uma fonte única de consulta para operação, desenvolvimento, suporte e gestão.</p><Callout title="Princípio de uso"><p>Cada usuário visualiza apenas os módulos, produtos de robôs e ações autorizados ao seu perfil.</p></Callout></Section>
    <Section number="02" title="Navegação principal"><div className={styles.featureGrid}><Feature title="Minha página">Organização pessoal, tarefas e atalhos de fluxos.</Feature><Feature title="Dashboard">Indicadores, atualizações recentes e solicitações autorizadas.</Feature><Feature title="Robôs">Listagens segregadas por Integradores, Consulta Processual, Peticionamento e Movimento.</Feature><Feature title="Fluxos">Documentação visual dos processos e integrações.</Feature><Feature title="Configurações">Usuários, clientes, cadastros técnicos, perfis e permissões.</Feature><Feature title="Documentação">Material institucional reservado ao Master.</Feature></div></Section>
    <Section number="03" title="Cadastro e manutenção de Robôs"><Checklist items={["Selecione o produto correto antes do cadastro.", "Preencha identificação, ambiente, execução e capacidade.", "Robôs Integradores exigem Cliente; os demais podem ser cadastrados sem esse vínculo.", "Stacks, filas, pacotes e Commands utilizam os cadastros técnicos existentes.", "Revise as informações e salve somente pelo botão de publicação.", "Use o histórico para acompanhar alterações e versões."]} /><p>Na importação por planilha, o produto da tela é preenchido no modelo. Novos valores técnicos podem ser cadastrados conforme as regras administrativas configuradas.</p></Section>
    <Section number="04" title="Fluxos, notas e documentação"><p>Fluxos representam visualmente robôs, sistemas, decisões e conexões. Notas e anotações aceitam formatação, tópicos e checklists. A documentação de cada robô mantém conteúdo técnico e histórico sem substituir o cadastro operacional.</p></Section>
    <Section number="05" title="Perfis e Controle de Acesso"><p>A Central de Controle de Acesso organiza permissões por perfil, módulo, submódulo e ação. Os níveis rápidos são Sem acesso, Somente leitura, Personalizado e Acesso total.</p><Checklist items={["Fechar o drawer não salva alterações.", "Aplicar alterações leva a configuração ao rascunho geral.", "Salvar alterações persiste a matriz.", "O perfil Master é protegido.", "A ausência de permissão remove menus e bloqueia URLs e operações."]} /></Section>
    <Section number="06" title="Boas práticas operacionais"><Checklist items={["Mantenha nomes técnicos e versões padronizados.", "Evite compartilhar contas; cada pessoa deve possuir seu usuário.", "Registre alterações relevantes no histórico.", "Revise periodicamente perfis, clientes e acessos.", "Use ambientes de Teste ou Desenvolvimento antes de alterações produtivas."]} /></Section>
  </div>;
}

function Security() {
  return <div className={styles.body}>
    <Section number="01" title="Visão técnica"><p>O Robot Center utiliza aplicação web React/Next.js, autenticação Supabase Auth e PostgreSQL gerenciado pelo Supabase. A autorização combina sessão autenticada, RBAC, validações no servidor e Row Level Security no banco.</p><div className={styles.architecture}><span>Navegador</span><ChevronRight /><span>Next.js</span><ChevronRight /><span>Supabase API/Auth</span><ChevronRight /><span>PostgreSQL + RLS</span></div></Section>
    <Section number="02" title="Identidade e autenticação"><Checklist items={["Identidade gerenciada pelo Supabase Auth.", "Sessões validadas no servidor antes de rotas protegidas.", "Senhas não são armazenadas nas tabelas de perfil da aplicação.", "Credenciais administrativas permanecem exclusivamente no servidor.", "Recuperação e alteração de senha utilizam os fluxos autenticados."]} /><Callout title="Recomendação de infraestrutura" tone="amber"><p>Habilitar proteção contra senhas vazadas, MFA para perfis privilegiados e política corporativa de expiração/revisão de acessos.</p></Callout></Section>
    <Section number="03" title="Autorização em profundidade"><p>As permissões seguem Perfil → Módulo → Submódulo → Ação. A interface reduz ações disponíveis, o proxy protege rotas, APIs repetem a autorização e policies RLS limitam as linhas acessíveis.</p><Checklist items={["Master possui controles superiores e matriz protegida.", "Permissões de produtos segregam a leitura de Robôs.", "Escopo por Cliente limita registros quando aplicável.", "Funções RPC sensíveis validam sessão e capacidade específica.", "Service role nunca é exposta no navegador."]} /></Section>
    <Section number="04" title="Proteção de dados"><div className={styles.featureGrid}><Feature title="Em trânsito">Obrigatoriedade de HTTPS/TLS nos ambientes publicados.</Feature><Feature title="Em repouso">Proteções do provedor e controles do PostgreSQL gerenciado.</Feature><Feature title="Segregação">RLS, vínculos por cliente e permissões por recurso.</Feature><Feature title="Auditoria">Campos de criação/alteração, históricos e registros funcionais.</Feature></div></Section>
    <Section number="05" title="Operação e monitoramento"><Checklist items={["Centralizar logs de aplicação, autenticação e banco.", "Alertar falhas de login, erros recorrentes e operações privilegiadas.", "Manter backups e testar restauração periodicamente.", "Aplicar migrations por pipeline controlado e nunca manualmente em produção.", "Executar revisão de RLS e advisors após mudanças estruturais.", "Definir RPO, RTO e responsáveis por resposta a incidentes."]} /></Section>
    <Section number="06" title="Responsabilidades da Infraestrutura"><p>A infraestrutura deve controlar variáveis de ambiente, domínios, certificados, secrets, retenção de logs, backups, observabilidade e separação entre Desenvolvimento, Homologação e Produção.</p><Callout title="Checklist mínimo para produção" tone="green"><Checklist items={["MFA em contas privilegiadas e no provedor.", "Secrets em cofre corporativo, com rotação.", "Backup validado por teste de restauração.", "Alertas de disponibilidade e erros.", "Plano de incidente e contatos definidos."]} /></Callout></Section>
  </div>;
}

function Migration() {
  return <div className={styles.body}>
    <Section number="01" title="Resumo executivo"><p>A migração é tecnicamente possível, mas deve ser motivada por requisitos claros de soberania, integração corporativa, custo, desempenho ou operação. A arquitetura atual é relacional e utiliza recursos nativos de PostgreSQL; portanto, um PostgreSQL interno apresenta menor risco que uma migração integral para MongoDB.</p><Callout title="Diretriz recomendada" tone="green"><p>Se houver exigência de banco interno, priorizar PostgreSQL compatível. Avaliar MongoDB apenas para domínios documentais específicos ou em arquitetura híbrida.</p></Callout></Section>
    <Section number="02" title="Cenários avaliados"><div className={styles.comparison}><Comparison title="Manter Supabase Cloud" tag="Menor esforço" items={["Auth, PostgreSQL, RLS e Realtime integrados", "Operação e atualização gerenciadas", "Menor carga para Infraestrutura"]} /><Comparison title="PostgreSQL interno" tag="Menor risco de migração" items={["Preserva modelo relacional e SQL", "Exige substituir ou hospedar Auth, API e Realtime", "Infra assume backup, HA, patches e monitoramento"]} /><Comparison title="MongoDB" tag="Maior transformação" items={["Bom para documentos flexíveis e leitura agregada", "Exige redesenho de relações, constraints e RLS", "Transações e autorização precisam ser reimplementadas"]} /></div></Section>
    <Section number="03" title="Por que PostgreSQL interno é mais aderente"><Checklist items={["O modelo atual possui relacionamentos, chaves estrangeiras e constraints.", "A autorização utiliza policies RLS e funções PostgreSQL.", "Históricos, perfis, robôs, fluxos e permissões exigem consistência transacional.", "Migrations existentes podem ser adaptadas a PostgreSQL compatível.", "A camada React/Next.js pode ser preservada com troca controlada do acesso a dados."]} /></Section>
    <Section number="04" title="Quando MongoDB pode fazer sentido"><p>MongoDB pode ser adequado para snapshots de documentação, telemetria volumosa, eventos, logs ou estruturas de conteúdo altamente variáveis. Para cadastros transacionais e RBAC, a adoção integral aumentaria a complexidade.</p><div className={styles.featureGrid}><Feature title="Boa aderência">Documentos, eventos, logs e payloads heterogêneos.</Feature><Feature title="Aderência moderada">Fluxos como documentos versionados, após análise de consultas.</Feature><Feature title="Baixa aderência">RBAC, usuários, clientes e vínculos com forte integridade.</Feature><Feature title="Modelo híbrido">PostgreSQL transacional e MongoDB para cargas documentais específicas.</Feature></div></Section>
    <Section number="05" title="Impactos obrigatórios"><Checklist items={["Substituição ou adaptação do Supabase Auth.", "Nova camada de acesso a dados e autorização no backend.", "Reimplementação das policies RLS fora do banco, se não houver PostgreSQL.", "Estratégia para Realtime e notificações.", "Conversão e validação dos dados históricos.", "Novos processos de backup, disaster recovery, observabilidade e patches.", "Testes de segurança, carga, regressão e reconciliação de dados."]} /></Section>
    <Section number="06" title="Plano seguro de migração"><ol className={styles.steps}><li><span>1</span><div><strong>Discovery</strong><p>Mapear SLAs, volume, integrações, requisitos legais e custos.</p></div></li><li><span>2</span><div><strong>Prova de conceito</strong><p>Migrar um domínio não crítico e medir desempenho e operação.</p></div></li><li><span>3</span><div><strong>Camada de compatibilidade</strong><p>Desacoplar a aplicação do provedor preservando contratos.</p></div></li><li><span>4</span><div><strong>Dupla escrita controlada</strong><p>Sincronizar e reconciliar dados durante uma janela definida.</p></div></li><li><span>5</span><div><strong>Cutover e rollback</strong><p>Trocar com critérios objetivos, monitoramento e retorno testado.</p></div></li></ol></Section>
    <Section number="07" title="Decisão sugerida"><p>Realizar primeiro uma avaliação de PostgreSQL interno versus permanência no Supabase, considerando custo total de propriedade — equipe, disponibilidade, segurança e suporte. MongoDB deve entrar na análise como complemento ou somente após comprovação de benefício mensurável.</p><a className={styles.external} href="https://www.postgresql.org/docs/" target="_blank" rel="noreferrer">Referência oficial PostgreSQL <ExternalLink size={13} /></a></Section>
  </div>;
}

function ExecutivePresentation() {
  return <div className={styles.body}>
    <Section number="01" title="Antes da solução: o problema"><p>À medida que a operação cresce, também cresce o volume de informações sobre robôs, ambientes, versões, comandos, Stacks, filas, clientes, responsáveis e configurações. Quando esses dados ficam distribuídos entre planilhas, mensagens, documentos e conhecimento individual, a empresa perde velocidade e previsibilidade.</p><div className={styles.featureGrid}><Feature title="Informação descentralizada">Dados importantes ficam espalhados em fontes diferentes.</Feature><Feature title="Dependência de pessoas">Parte do conhecimento permanece somente com quem acompanha o robô.</Feature><Feature title="Baixa rastreabilidade">É difícil identificar rapidamente versões, mudanças e responsáveis.</Feature><Feature title="Visão fragmentada">Gestores não possuem uma leitura consolidada da operação.</Feature></div></Section>
    <Section number="02" title="Os impactos no dia a dia"><Checklist items={["Mais tempo gasto procurando informações antes de agir.", "Dificuldade para responder dúvidas operacionais e técnicas.", "Risco de utilizar configurações ou versões desatualizadas.", "Onboarding mais lento de novos integrantes.", "Baixa visibilidade sobre capacidade, status e evolução dos robôs.", "Decisões gerenciais dependentes de consolidações manuais."]} /><Callout title="O ponto central" tone="amber"><p>O problema não é apenas armazenar dados. É transformar informações dispersas em conhecimento confiável, acessível e governável.</p></Callout></Section>
    <Section number="03" title="Nasce o Robot Center"><p>O Robot Center surge como um ponto central para reunir o conhecimento operacional e técnico dos robôs. A proposta é facilitar o trabalho diário das equipes e criar uma base consistente para gestão, acompanhamento e controle de toda a automação.</p><Callout title="Uma fonte única de referência"><p>Em vez de procurar em diferentes locais, a equipe consulta uma plataforma organizada, atualizada e protegida por perfis de acesso.</p></Callout></Section>
    <Section number="04" title="Como a solução organiza a operação"><div className={styles.featureGrid}><Feature title="Catálogo central de robôs">Identificação, produto, cliente, ambiente, Stack, Command, fila, status e versão.</Feature><Feature title="Segregação por produto">Integradores, Consulta Processual, Peticionamento e Movimento.</Feature><Feature title="Histórico e atualizações">Rastreabilidade das mudanças importantes realizadas no sistema.</Feature><Feature title="Fluxos e documentação">Representação visual e conhecimento técnico próximos do robô.</Feature><Feature title="Solicitações de Stack">Processo estruturado entre solicitantes e responsáveis pela análise.</Feature><Feature title="Controle de acesso">Cada perfil visualiza e executa somente aquilo que foi autorizado.</Feature></div></Section>
    <Section number="05" title="Valor imediato para as equipes"><Checklist items={["Redução do tempo para localizar informações.", "Padronização de cadastros e configurações técnicas.", "Melhor comunicação entre Operação, Desenvolvimento, Suporte e Gestão.", "Mais segurança para manutenção e publicação de alterações.", "Visibilidade consolidada por dashboard e indicadores.", "Preservação do conhecimento da empresa."]} /></Section>
    <Section number="06" title="Além de um catálogo"><p>O Robot Center pode evoluir de uma central de consulta para uma ferramenta de gerenciamento interno dos robôs. A mesma base organizada permite acompanhar governança, capacidade, qualidade, responsabilidades e desempenho operacional.</p><div className={styles.comparison}><Comparison title="Hoje" tag="Centralização" items={["Cadastro confiável", "Consulta rápida", "Histórico e documentação"]} /><Comparison title="Evolução" tag="Gestão" items={["Indicadores gerenciais", "Governança e auditoria", "Acompanhamento de demandas"]} /><Comparison title="Visão futura" tag="Controle operacional" items={["Saúde e execução dos robôs", "Alertas e capacidade", "Decisões orientadas por dados"]} /></div></Section>
    <Section number="07" title="Possibilidades futuras"><Checklist items={["Dashboards por produto, Stack, cliente, tribunal e ambiente.", "Indicadores de disponibilidade, falhas e produtividade.", "Gestão de ciclo de vida e obsolescência de versões.", "Integração com execução, monitoramento e filas operacionais.", "Alertas preventivos e acompanhamento de incidentes.", "Relatórios executivos para planejamento e priorização."]} /><p>Essas evoluções devem ser graduais e construídas sobre a governança e a qualidade dos dados já centralizados.</p></Section>
    <Section number="08" title="Mensagem para os gestores"><Callout title="O Robot Center organiza o presente e prepara o futuro" tone="green"><p>A ferramenta reduz a dispersão de conhecimento, melhora o dia a dia das equipes e cria uma fundação para administrar todo o ecossistema de robôs com mais segurança, clareza e inteligência.</p></Callout></Section>
    <Section number="09" title="Sugestão de encerramento"><p>O próximo passo é consolidar o Robot Center como fonte oficial de informação dos robôs, definir responsáveis pela atualização dos dados e priorizar os indicadores gerenciais que mais apoiam a operação e a liderança.</p><Checklist items={["Validar o Robot Center como fonte oficial.", "Definir responsáveis e rotina de atualização.", "Selecionar os primeiros indicadores executivos.", "Planejar integrações de monitoramento em fases."]} /></Section>
  </div>;
}

function Feature({ title, children }: { title: string; children: ReactNode }) { return <div className={styles.feature}><strong>{title}</strong><p>{children}</p></div>; }
function Comparison({ title, tag, items }: { title: string; tag: string; items: string[] }) { return <div className={styles.comparisonCard}><span>{tag}</span><h4>{title}</h4><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
