"use client";

import { ArrowDown, ArrowLeft, ArrowUp, BookOpen, GripVertical, History, Play, Plus, Save, Send, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/layout/AppShell";
import SettingsNavigation from "@/components/settings/SettingsNavigation";
import { useTutorial } from "@/tutorial/TutorialProvider";
import { TOUR_PAGE_CATALOG, findTourPage } from "@/tutorial/targetCatalog";
import type { TutorialDraftStep, TutorialEditorData, TutorialPlacement } from "@/tutorial/adminTypes";

interface RoleOption { id: string; codigo: string; nome: string }
const placements: Array<{ value: TutorialPlacement; label: string }> = [{ value: "top", label: "Acima" }, { value: "right", label: "Direita" }, { value: "bottom", label: "Abaixo" }, { value: "left", label: "Esquerda" }];

export default function TutorialEditorPage({ tutorialId }: { tutorialId: string }) {
  const tour = useTutorial(); const [data, setData] = useState<TutorialEditorData | null>(null); const [roles, setRoles] = useState<RoleOption[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [publishOpen, setPublishOpen] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [dragged, setDragged] = useState<number | null>(null);

  async function load() { setLoading(true); setError(""); try { const [detailResponse, listResponse] = await Promise.all([fetch(`/api/admin/tutorials/${tutorialId}`, { cache: "no-store" }), fetch("/api/admin/tutorials", { cache: "no-store" })]); const detail = await detailResponse.json() as { tutorial?: TutorialEditorData; error?: string }; const list = await listResponse.json() as { roles?: RoleOption[] }; if (!detailResponse.ok || !detail.tutorial) throw new Error(detail.error ?? "Tutorial não encontrado."); setData(detail.tutorial); setRoles(list.roles ?? []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Não foi possível carregar o editor."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tutorialId]);
  useEffect(() => { if (data && new URLSearchParams(window.location.search).get("testar") === "1") tour.previewTutorial(data.name, data.steps); }, [data, tour.previewTutorial]);

  const nextVersion = (data?.currentVersion ?? 0) + 1;
  const changeStep = (index: number, patch: Partial<TutorialDraftStep>) => setData((current) => current ? { ...current, steps: current.steps.map((step, stepIndex) => stepIndex === index ? { ...step, ...patch } : step) } : current);
  const move = (from: number, to: number) => setData((current) => { if (!current || to < 0 || to >= current.steps.length) return current; const steps = [...current.steps]; const [step] = steps.splice(from, 1); steps.splice(to, 0, step); return { ...current, steps }; });
  function addStep() { const page = TOUR_PAGE_CATALOG[0]; const target = page.targets[0]; setData((current) => current ? { ...current, steps: [...current.steps, { id: crypto.randomUUID(), pageKey: page.key, targetKey: target.key, title: "Novo passo", description: "", placement: "bottom", conditionKey: target.conditionKey ?? null, enabled: true }] } : current); }
  function removeStep(index: number) { if (window.confirm("Excluir este passo do rascunho? A versão publicada não será alterada.")) setData((current) => current ? { ...current, steps: current.steps.filter((_, stepIndex) => stepIndex !== index) } : current); }

  async function save(showSuccess = true) { if (!data) return false; setSaving(true); setError(""); setMessage(""); try { const response = await fetch(`/api/admin/tutorials/${tutorialId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.name, audienceRoleId: data.audienceRoleId, steps: data.steps }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "Não foi possível salvar."); if (showSuccess) setMessage("Rascunho salvo."); return true; } catch (saveError) { setError(saveError instanceof Error ? saveError.message : "Não foi possível salvar."); return false; } finally { setSaving(false); } }
  async function publish() { if (!data || !(await save(false))) return; setSaving(true); try { const response = await fetch(`/api/admin/tutorials/${tutorialId}/publish`, { method: "POST" }); const payload = await response.json() as { version?: number; error?: string }; if (!response.ok) throw new Error(payload.error ?? "Não foi possível publicar."); setPublishOpen(false); setMessage(`Versão v${payload.version} publicada com sucesso.`); await load(); } catch (publishError) { setError(publishError instanceof Error ? publishError.message : "Não foi possível publicar."); } finally { setSaving(false); } }

  if (loading) return <AppShell title="Editor de tutorial"><div className="tutorial-message">Carregando editor...</div></AppShell>;
  if (!data) return <AppShell title="Editor de tutorial"><div className="tutorial-message is-error">{error || "Tutorial não encontrado."}</div></AppShell>;
  return <AppShell title="Editor de tutorial"><section className="tutorial-editor-page">
    <div className="tutorial-breadcrumb"><Link href="/configuracoes/tutoriais"><ArrowLeft size={14} /> Tutoriais</Link><span>/</span><span>{data.name}</span></div>
    <header className="tutorial-editor-heading"><div><span>EDITOR DE TUTORIAL</span><h1>{data.name}</h1><p>Rascunho independente da versão publicada {data.currentVersion ? `v${data.currentVersion}` : "—"}.</p></div><div><button className="tutorial-secondary-button" onClick={() => tour.previewTutorial(data.name, data.steps)}><Play size={14} /> Testar</button><button className="tutorial-secondary-button" disabled={saving} onClick={() => void save()}><Save size={14} /> Salvar</button><button className="tutorial-primary-button" disabled={saving} onClick={() => setPublishOpen(true)}><Send size={14} /> Publicar</button></div></header>
    <SettingsNavigation active="tutoriais" />
    <div className="tutorial-editor-meta"><label>Nome<input value={data.name} onChange={(event) => setData({ ...data, name: event.target.value })} /></label><label>Público<select value={data.audienceRoleId} onChange={(event) => setData({ ...data, audienceRoleId: event.target.value })}>{roles.map((role) => <option key={role.id} value={role.id}>{role.nome}</option>)}</select></label><div><span>Status</span><strong>{data.status === "published" ? "Publicado" : data.status === "inactive" ? "Inativo" : "Rascunho"}</strong></div><div><span>Próxima versão</span><strong>v{nextVersion}</strong></div></div>
    {message && <div className="tutorial-message is-success">{message}</div>}{error && <div className="tutorial-message is-error">{error}</div>}
    <div className="tutorial-editor-section-heading"><div><BookOpen size={16} /><span>Passos</span><small>{data.steps.length} cadastrados</small></div><button className="tutorial-primary-button" onClick={addStep}><Plus size={14} /> Adicionar passo</button></div>
    <div className="tutorial-step-list">{data.steps.map((step, index) => { const page = findTourPage(step.pageKey) ?? TOUR_PAGE_CATALOG[0]; return <article key={step.id} className="tutorial-step-card" draggable onDragStart={() => setDragged(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragged !== null) move(dragged, index); setDragged(null); }}><div className="tutorial-step-number"><GripVertical size={15} /><strong>{index + 1}</strong></div><div className="tutorial-step-fields"><label>Título<input value={step.title} onChange={(event) => changeStep(index, { title: event.target.value })} /></label><label className="is-wide">Descrição<textarea rows={2} value={step.description} onChange={(event) => changeStep(index, { description: event.target.value })} /></label><label>Página<select value={step.pageKey} onChange={(event) => { const nextPage = findTourPage(event.target.value) ?? TOUR_PAGE_CATALOG[0]; const target = nextPage.targets[0]; changeStep(index, { pageKey: nextPage.key, targetKey: target.key, conditionKey: target.conditionKey ?? null }); }}>{TOUR_PAGE_CATALOG.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label>Elemento<select value={step.targetKey} onChange={(event) => { const target = page.targets.find((item) => item.key === event.target.value); changeStep(index, { targetKey: event.target.value, conditionKey: target?.conditionKey ?? null }); }}>{page.targets.map((target) => <option key={target.key} value={target.key}>{target.label}</option>)}</select></label><label>Posição<select value={step.placement} onChange={(event) => changeStep(index, { placement: event.target.value as TutorialPlacement })}>{placements.map((placement) => <option key={placement.value} value={placement.value}>{placement.label}</option>)}</select></label><label className="tutorial-enabled"><input type="checkbox" checked={step.enabled} onChange={(event) => changeStep(index, { enabled: event.target.checked })} /> Passo habilitado</label></div><div className="tutorial-step-actions"><button title="Mover para cima" disabled={index === 0} onClick={() => move(index, index - 1)}><ArrowUp size={14} /></button><button title="Mover para baixo" disabled={index === data.steps.length - 1} onClick={() => move(index, index + 1)}><ArrowDown size={14} /></button><button className="is-danger" title="Excluir passo" onClick={() => removeStep(index)}><Trash2 size={14} /></button></div></article>; })}</div>
    {data.versions.length > 0 && <section className="tutorial-history"><h2><History size={16} /> Histórico</h2>{data.versions.map((version) => <div key={version.id}><strong>v{version.version}</strong><span>{version.id === data.versions[0]?.id ? "Atual" : "Histórico"}</span><time>{new Date(version.publishedAt).toLocaleString("pt-BR")}</time></div>)}</section>}
    {publishOpen && <div className="tutorial-publish-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) setPublishOpen(false); }}><section className="tutorial-publish-dialog" role="dialog" aria-modal="true" aria-labelledby="tutorial-publish-title"><header><div><span>CONFIRMAR PUBLICAÇÃO</span><h2 id="tutorial-publish-title">Publicar nova versão?</h2></div><button type="button" aria-label="Fechar confirmação" disabled={saving} onClick={() => setPublishOpen(false)}><X size={17} /></button></header><p>A versão publicada ficará disponível para o público selecionado.</p><dl><div><dt>Versão atual</dt><dd>{data.currentVersion ? `v${data.currentVersion}` : "Nenhuma"}</dd></div><div><dt>Nova versão</dt><dd>v{nextVersion}</dd></div><div><dt>Passos habilitados</dt><dd>{data.steps.filter((step) => step.enabled).length}</dd></div><div><dt>Público</dt><dd>{roles.find((item) => item.id === data.audienceRoleId)?.nome ?? data.audienceRoleName}</dd></div></dl><footer><button type="button" className="tutorial-secondary-button" disabled={saving} onClick={() => setPublishOpen(false)}>Cancelar</button><button type="button" className="tutorial-primary-button" disabled={saving} onClick={() => void publish()}><Send size={14} /> {saving ? "Publicando..." : `Publicar v${nextVersion}`}</button></footer></section></div>}
  </section></AppShell>;
}
